server:
  port: 80 #端口号

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-gateway # 服务名

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # nacos服务地址

    gateway:
      discovery:
        locator:
          enabled: true  # gateway可以发现nacos中的微服务，并自动生成转发路由

      #spring:
      # cloud:
      #   gateway:
      routes:
        - id: service-hosp
          uri: lb://service-hosp
          predicates:
            - Path=/*/hosp/**
        - id: service-cmn
          uri: lb://service-cmn
          predicates:
            - Path=/*/cmn/**
#        - id: service-oss
#          uri: lb://service-oss
#          predicates:
#            - Path=/*/oss/**

